language: node_js
before_install:
  - git clone git://github.com/ninja-build/ninja.git && cd ninja && ./configure.py --bootstrap
env:
  global:
    - NINJA=../../../ninja/ninja
script:
  npm install && npm run build && npm test
node_js:
  - 4
  - 5
  - 6
